### ISSUE TITLE
Searching in data fails

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [michitux/dokuwiki-plugin-searchtext#9]
Hi,

when I search for an entry in a data table (plugin data), there comes up an error message:

*Catchable fatal error: Argument 3 passed to helper_plugin_data::_formatData() must be an instance of Doku_Renderer_xhtml, instance of renderer_plugin_text given, called in /opt/lampp/htdocs/wiki/lib/plugins/data/syntax/entry.php on line 193 and defined in /opt/lampp/htdocs/wiki/lib/plugins/data/helper.php on line 216*

The search result breaks after this message, so that the rest of the search results isn't shown.

Regards Juergen

**Comment by michitux** [comment]
I've just released a new version of the text plugin, this should fix this issue. You should also update the searchindex plugin as I've added a feature which automatically updates the search index when the text plugin was updated.

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much, it works

Regards
Juergen
